### ISSUE TITLE
when open example get Error loading theme: notFound 

### ISSUE THREAD

**Issue by mohammadshalhoob** [yonaskolb/Stylist#1]
Error loading theme: notFound , when open example 

test on xcode 8.3.3 , iphone 4 , ios 9.3.

i fix it like this , in AppDelegate didFinishLaunchingWithOptions .

        if let path = Bundle.main.url(forResource: "Style", withExtension: "yaml") {
            Stylist.shared.watch(url: path, animateChanges: true) { error in
                print("Error loading theme:\n\(error)")
            }

        }

thanks

**Comment by yonaskolb** [comment]
Interesting, I'm not seeing that error. I'm sure it was working in Xcode 8 and it's working for me now in Xcode 9.

**Comment by yonaskolb** [comment]
@mohammadshalhoob I just updated to Swift 4 in master. You can see if it works for you in Xcode 9

**Comment by mohammadshalhoob** [comment]
ok i will test it ,

thanks

**Comment by yonaskolb** [comment]
Any luck @mohammadshalhoob?

**Comment by yonaskolb** [comment]
Closing this for now. Let me know if you have any problems @mohammadshalhoob
