### ISSUE TITLE
Not working when built using Carthage

### ISSUE THREAD

**Issue by drekka** [yonaskolb/Stylist#8]
I've tried to include Stylist in my Carthage dependencies. But there are two issues I've found. Firstly Stylist needs a Cartfile like this:

```
github "krzysztofzablocki/KZFileWatchers"
github "jpsim/Yams"
```

However when I then tried to get Carthage to update, it tells me there is a circular dependency. 

So next I tried adding KZFileWatcher and Yams to my project's Cartfile. It built ok, but when the app started, it checked the frameworks and crashes, reporting that Yams is version 0.0.0 instead of the required 1.0.0.

So at the moment I can't use Stylist. 

Any ideas?

**Comment by yonaskolb** [comment]
Released in 0.2.1
